on:
  - push
  - pull_request

jobs:
  runs-on: ubuntu-latest

  steps:
    build:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
        node-version: "14"

      - name: Run build & test
        run: |
          npm run build
          npm run test
